name: pipeline-deploy-s3
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - name: frontend install
      run: npm --prefix frontend install
    - name: frontend build
      run: npm --prefix frontend run build
    - name: upload frontend build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: frontend/.next/server/app
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_EC2_METADATA_DISABLED: true
      BUCKET_S3: ${{ vars.BUCKET_S3 }}
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: build
        path: frontend/.next/server/app
    - run: aws s3 cp frontend/.next/server/app s3://$BUCKET_S3 --recursive --acl public-read
